// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCounter() {
  return window['go']['main']['App']['GetCounter']();
}

export function Increment() {
  return window['go']['main']['App']['Increment']();
}
